// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxyxvhmvcfwfimtjigdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4eXh2aG12Y2Z3ZmltdGppZ2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzQ0MDksImV4cCI6MjA2NzIxMDQwOX0.JNOVtR0wb81SAHyys3W9PWJi7fAj_Q3-Xax5w4Oj02k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});